services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=appointment_system
      - MYSQL_ROOT_PASSWORD=mysqlPW
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysqlPW
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql-volume:
    driver: local
