services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=appointment_system
      - MYSQL_ROOT_PASSWORD=mysqlPW
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-volume:
    driver: local
